profile=high-quality
vo=gpu-next
# hwdec=auto-safe
# gpu-api=vulkan
target-colorspace-hint=auto

keep-open=yes

audio-channels=stereo

directory-mode=ignore

osd-bar=no
border=no

screenshot-directory="~~desktop/"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

audio-file-auto=fuzzy

[no-video]
profile-cond=not (vid)
input-commands="script-binding uosc/toggle-ui"

[1080p+]
profile-cond=width >= 1920
fullscreen=yes